### ISSUE TITLE
Android P Support

### ISSUE THREAD

**Issue by hackel** [InFlames03/Oreo-Theme#12]
Just wondering if you have any plans to work on creating an Android P version of Sai's Dark Theme.  The built-in dark theme seems to take care of most of Android System / System UI, but the notifications and settings are still white.  (Except for the YouTube now playing notification, which is oddly dark).

Thanks for your work on this excellent theme and keeping it open source!

**Comment by MSF-Jarvis** [comment]
Android P has been supported since commit 92a2d47764bbc102e2f35d1fff26deb04053020e

**Comment by hackel** [comment]
Awesome, thanks!  Look forward to the release!
