### ISSUE TITLE
Black background not available on version 3

### ISSUE THREAD

**Issue by g0to** [InFlames03/Oreo-Theme#5]
After upgrading to version 3 from version 2, the tiles black background doesn't work anymore. It's only Oreo's default transparent grey now. 

Is there a way to bring the completely black background on the tiles again?

Thanks.

**Comment by InFlames03** [comment]
Works totally fine on my end on both 8.0 and 8.1. Same is the case with my testers. Please uninstall the overlays -> install them again while making sure all the configurations are correct and that you've chosen the correct OS version.

**Comment by InFlames03** [comment]
Also, perform a system reboot once you're done reinstalling the stuff

**Comment by g0to** [comment]
I've tried uninstalling all my themes, rebooting, and installing only this
theme but had no success in having the black background back.

Do you happen to have a Pixel 2 for testing running the latest version of
Oreo?

**Comment by InFlames03** [comment]
Fun fact: my daily driver is a Pixel 2 XL

**Comment by InFlames03** [comment]
Ok, I may have tracked down the issue after some investigation. Is your wallpaper dark? Android 8.1's adaptive System UI colour feature maybe interfering with Substratum themes.

**Comment by g0to** [comment]
Yes. My wallpaper is dark. I'm using the same one that I was using with the theme's previous version, which was working fine.

**Comment by InFlames03** [comment]
Already pushed an update to fix your issue. Grab version 4
